spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookie
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: localhost
    port: 6379
    timeout: 1000
  cache:
    redis:
      cache-null-values: false
      use-key-prefix: true
      key-prefix: library
      time-to-live: 60000
server:
  error:
    include-message: always
